services:
  db:
    image: pgvector/pgvector:pg17
    container_name: blog-postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blog-redis-db
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: blog-pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: blog-backend-go-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      GIN_MODE: release
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    container_name: blog-frontend-nextjs-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
        - "9009:3000"
    depends_on:
      - backend

  extractor:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    container_name: blog-extractor-python-app
    restart: always
    ports:
      - "5002:5002"

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
