root = "./cmd/server"
tmp_dir = "../../tmp"

[build]
  cmd = "go build -o ../../tmp/main ."
  bin = "../../tmp/main"
  full_bin = "../../tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["../../tmp", "vendor"]
  follow_symlink = true
  kill_delay = "2s"

[log]
  time = true
